// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// DoubleClick
void DoubleClick(int x, int y);
RcppExport SEXP clickpaste_DoubleClick(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type y(ySEXP);
    DoubleClick(x, y);
    return R_NilValue;
END_RCPP
}
// get_point_x
double get_point_x();
RcppExport SEXP clickpaste_get_point_x() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_point_x());
    return rcpp_result_gen;
END_RCPP
}
// get_point_y
double get_point_y();
RcppExport SEXP clickpaste_get_point_y() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_point_y());
    return rcpp_result_gen;
END_RCPP
}
// shift
int shift();
RcppExport SEXP clickpaste_shift() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(shift());
    return rcpp_result_gen;
END_RCPP
}
// a_1
int a_1();
RcppExport SEXP clickpaste_a_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(a_1());
    return rcpp_result_gen;
END_RCPP
}
// b_1
int b_1();
RcppExport SEXP clickpaste_b_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(b_1());
    return rcpp_result_gen;
END_RCPP
}
// c_1
int c_1();
RcppExport SEXP clickpaste_c_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(c_1());
    return rcpp_result_gen;
END_RCPP
}
// d_1
int d_1();
RcppExport SEXP clickpaste_d_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(d_1());
    return rcpp_result_gen;
END_RCPP
}
// e_1
int e_1();
RcppExport SEXP clickpaste_e_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(e_1());
    return rcpp_result_gen;
END_RCPP
}
// f_1
int f_1();
RcppExport SEXP clickpaste_f_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(f_1());
    return rcpp_result_gen;
END_RCPP
}
// g_1
int g_1();
RcppExport SEXP clickpaste_g_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(g_1());
    return rcpp_result_gen;
END_RCPP
}
// h_1
int h_1();
RcppExport SEXP clickpaste_h_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(h_1());
    return rcpp_result_gen;
END_RCPP
}
// i_1
int i_1();
RcppExport SEXP clickpaste_i_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(i_1());
    return rcpp_result_gen;
END_RCPP
}
// j_1
int j_1();
RcppExport SEXP clickpaste_j_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(j_1());
    return rcpp_result_gen;
END_RCPP
}
// k_1
int k_1();
RcppExport SEXP clickpaste_k_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(k_1());
    return rcpp_result_gen;
END_RCPP
}
// l_1
int l_1();
RcppExport SEXP clickpaste_l_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(l_1());
    return rcpp_result_gen;
END_RCPP
}
// m_1
int m_1();
RcppExport SEXP clickpaste_m_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(m_1());
    return rcpp_result_gen;
END_RCPP
}
// n_1
int n_1();
RcppExport SEXP clickpaste_n_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(n_1());
    return rcpp_result_gen;
END_RCPP
}
// o_1
int o_1();
RcppExport SEXP clickpaste_o_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(o_1());
    return rcpp_result_gen;
END_RCPP
}
// p_1
int p_1();
RcppExport SEXP clickpaste_p_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(p_1());
    return rcpp_result_gen;
END_RCPP
}
// q_1
int q_1();
RcppExport SEXP clickpaste_q_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(q_1());
    return rcpp_result_gen;
END_RCPP
}
// r_1
int r_1();
RcppExport SEXP clickpaste_r_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(r_1());
    return rcpp_result_gen;
END_RCPP
}
// s_1
int s_1();
RcppExport SEXP clickpaste_s_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(s_1());
    return rcpp_result_gen;
END_RCPP
}
// t_1
int t_1();
RcppExport SEXP clickpaste_t_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(t_1());
    return rcpp_result_gen;
END_RCPP
}
// u_1
int u_1();
RcppExport SEXP clickpaste_u_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(u_1());
    return rcpp_result_gen;
END_RCPP
}
// v_1
int v_1();
RcppExport SEXP clickpaste_v_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(v_1());
    return rcpp_result_gen;
END_RCPP
}
// w_1
int w_1();
RcppExport SEXP clickpaste_w_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(w_1());
    return rcpp_result_gen;
END_RCPP
}
// x_1
int x_1();
RcppExport SEXP clickpaste_x_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(x_1());
    return rcpp_result_gen;
END_RCPP
}
// y_1
int y_1();
RcppExport SEXP clickpaste_y_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(y_1());
    return rcpp_result_gen;
END_RCPP
}
// z_1
int z_1();
RcppExport SEXP clickpaste_z_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(z_1());
    return rcpp_result_gen;
END_RCPP
}
// zero_1
int zero_1();
RcppExport SEXP clickpaste_zero_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(zero_1());
    return rcpp_result_gen;
END_RCPP
}
// one_1
int one_1();
RcppExport SEXP clickpaste_one_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(one_1());
    return rcpp_result_gen;
END_RCPP
}
// two_1
int two_1();
RcppExport SEXP clickpaste_two_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(two_1());
    return rcpp_result_gen;
END_RCPP
}
// three_1
int three_1();
RcppExport SEXP clickpaste_three_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(three_1());
    return rcpp_result_gen;
END_RCPP
}
// four_1
int four_1();
RcppExport SEXP clickpaste_four_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(four_1());
    return rcpp_result_gen;
END_RCPP
}
// five_1
int five_1();
RcppExport SEXP clickpaste_five_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(five_1());
    return rcpp_result_gen;
END_RCPP
}
// six_1
int six_1();
RcppExport SEXP clickpaste_six_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(six_1());
    return rcpp_result_gen;
END_RCPP
}
// seven_1
int seven_1();
RcppExport SEXP clickpaste_seven_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(seven_1());
    return rcpp_result_gen;
END_RCPP
}
// eight_1
int eight_1();
RcppExport SEXP clickpaste_eight_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(eight_1());
    return rcpp_result_gen;
END_RCPP
}
// nine_1
int nine_1();
RcppExport SEXP clickpaste_nine_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(nine_1());
    return rcpp_result_gen;
END_RCPP
}
// funtion_1
int funtion_1();
RcppExport SEXP clickpaste_funtion_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(funtion_1());
    return rcpp_result_gen;
END_RCPP
}
// funtion_2
int funtion_2();
RcppExport SEXP clickpaste_funtion_2() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(funtion_2());
    return rcpp_result_gen;
END_RCPP
}
// funtion_3
int funtion_3();
RcppExport SEXP clickpaste_funtion_3() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(funtion_3());
    return rcpp_result_gen;
END_RCPP
}
// funtion_4
int funtion_4();
RcppExport SEXP clickpaste_funtion_4() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(funtion_4());
    return rcpp_result_gen;
END_RCPP
}
// funtion_5
int funtion_5();
RcppExport SEXP clickpaste_funtion_5() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(funtion_5());
    return rcpp_result_gen;
END_RCPP
}
// funtion_6
int funtion_6();
RcppExport SEXP clickpaste_funtion_6() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(funtion_6());
    return rcpp_result_gen;
END_RCPP
}
// funtion_7
int funtion_7();
RcppExport SEXP clickpaste_funtion_7() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(funtion_7());
    return rcpp_result_gen;
END_RCPP
}
// funtion_8
int funtion_8();
RcppExport SEXP clickpaste_funtion_8() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(funtion_8());
    return rcpp_result_gen;
END_RCPP
}
// funtion_9
int funtion_9();
RcppExport SEXP clickpaste_funtion_9() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(funtion_9());
    return rcpp_result_gen;
END_RCPP
}
// funtion_10
int funtion_10();
RcppExport SEXP clickpaste_funtion_10() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(funtion_10());
    return rcpp_result_gen;
END_RCPP
}
// funtion_11
int funtion_11();
RcppExport SEXP clickpaste_funtion_11() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(funtion_11());
    return rcpp_result_gen;
END_RCPP
}
// funtion_12
int funtion_12();
RcppExport SEXP clickpaste_funtion_12() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(funtion_12());
    return rcpp_result_gen;
END_RCPP
}
// enter_1
int enter_1();
RcppExport SEXP clickpaste_enter_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(enter_1());
    return rcpp_result_gen;
END_RCPP
}
// backspace_1
int backspace_1();
RcppExport SEXP clickpaste_backspace_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(backspace_1());
    return rcpp_result_gen;
END_RCPP
}
// delete_1
int delete_1();
RcppExport SEXP clickpaste_delete_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(delete_1());
    return rcpp_result_gen;
END_RCPP
}
// control_a
int control_a();
RcppExport SEXP clickpaste_control_a() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(control_a());
    return rcpp_result_gen;
END_RCPP
}
// alter_1
int alter_1();
RcppExport SEXP clickpaste_alter_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(alter_1());
    return rcpp_result_gen;
END_RCPP
}
// pageup_1
int pageup_1();
RcppExport SEXP clickpaste_pageup_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(pageup_1());
    return rcpp_result_gen;
END_RCPP
}
// pagedown_1
int pagedown_1();
RcppExport SEXP clickpaste_pagedown_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(pagedown_1());
    return rcpp_result_gen;
END_RCPP
}
// escape_1
int escape_1();
RcppExport SEXP clickpaste_escape_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(escape_1());
    return rcpp_result_gen;
END_RCPP
}
// paste_1
int paste_1();
RcppExport SEXP clickpaste_paste_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(paste_1());
    return rcpp_result_gen;
END_RCPP
}
// RightClick
void RightClick(int x, int y);
RcppExport SEXP clickpaste_RightClick(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type y(ySEXP);
    RightClick(x, y);
    return R_NilValue;
END_RCPP
}
// SingleClick
void SingleClick(int x, int y);
RcppExport SEXP clickpaste_SingleClick(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type y(ySEXP);
    SingleClick(x, y);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"clickpaste_DoubleClick", (DL_FUNC) &clickpaste_DoubleClick, 2},
    {"clickpaste_get_point_x", (DL_FUNC) &clickpaste_get_point_x, 0},
    {"clickpaste_get_point_y", (DL_FUNC) &clickpaste_get_point_y, 0},
    {"clickpaste_shift", (DL_FUNC) &clickpaste_shift, 0},
    {"clickpaste_a_1", (DL_FUNC) &clickpaste_a_1, 0},
    {"clickpaste_b_1", (DL_FUNC) &clickpaste_b_1, 0},
    {"clickpaste_c_1", (DL_FUNC) &clickpaste_c_1, 0},
    {"clickpaste_d_1", (DL_FUNC) &clickpaste_d_1, 0},
    {"clickpaste_e_1", (DL_FUNC) &clickpaste_e_1, 0},
    {"clickpaste_f_1", (DL_FUNC) &clickpaste_f_1, 0},
    {"clickpaste_g_1", (DL_FUNC) &clickpaste_g_1, 0},
    {"clickpaste_h_1", (DL_FUNC) &clickpaste_h_1, 0},
    {"clickpaste_i_1", (DL_FUNC) &clickpaste_i_1, 0},
    {"clickpaste_j_1", (DL_FUNC) &clickpaste_j_1, 0},
    {"clickpaste_k_1", (DL_FUNC) &clickpaste_k_1, 0},
    {"clickpaste_l_1", (DL_FUNC) &clickpaste_l_1, 0},
    {"clickpaste_m_1", (DL_FUNC) &clickpaste_m_1, 0},
    {"clickpaste_n_1", (DL_FUNC) &clickpaste_n_1, 0},
    {"clickpaste_o_1", (DL_FUNC) &clickpaste_o_1, 0},
    {"clickpaste_p_1", (DL_FUNC) &clickpaste_p_1, 0},
    {"clickpaste_q_1", (DL_FUNC) &clickpaste_q_1, 0},
    {"clickpaste_r_1", (DL_FUNC) &clickpaste_r_1, 0},
    {"clickpaste_s_1", (DL_FUNC) &clickpaste_s_1, 0},
    {"clickpaste_t_1", (DL_FUNC) &clickpaste_t_1, 0},
    {"clickpaste_u_1", (DL_FUNC) &clickpaste_u_1, 0},
    {"clickpaste_v_1", (DL_FUNC) &clickpaste_v_1, 0},
    {"clickpaste_w_1", (DL_FUNC) &clickpaste_w_1, 0},
    {"clickpaste_x_1", (DL_FUNC) &clickpaste_x_1, 0},
    {"clickpaste_y_1", (DL_FUNC) &clickpaste_y_1, 0},
    {"clickpaste_z_1", (DL_FUNC) &clickpaste_z_1, 0},
    {"clickpaste_zero_1", (DL_FUNC) &clickpaste_zero_1, 0},
    {"clickpaste_one_1", (DL_FUNC) &clickpaste_one_1, 0},
    {"clickpaste_two_1", (DL_FUNC) &clickpaste_two_1, 0},
    {"clickpaste_three_1", (DL_FUNC) &clickpaste_three_1, 0},
    {"clickpaste_four_1", (DL_FUNC) &clickpaste_four_1, 0},
    {"clickpaste_five_1", (DL_FUNC) &clickpaste_five_1, 0},
    {"clickpaste_six_1", (DL_FUNC) &clickpaste_six_1, 0},
    {"clickpaste_seven_1", (DL_FUNC) &clickpaste_seven_1, 0},
    {"clickpaste_eight_1", (DL_FUNC) &clickpaste_eight_1, 0},
    {"clickpaste_nine_1", (DL_FUNC) &clickpaste_nine_1, 0},
    {"clickpaste_funtion_1", (DL_FUNC) &clickpaste_funtion_1, 0},
    {"clickpaste_funtion_2", (DL_FUNC) &clickpaste_funtion_2, 0},
    {"clickpaste_funtion_3", (DL_FUNC) &clickpaste_funtion_3, 0},
    {"clickpaste_funtion_4", (DL_FUNC) &clickpaste_funtion_4, 0},
    {"clickpaste_funtion_5", (DL_FUNC) &clickpaste_funtion_5, 0},
    {"clickpaste_funtion_6", (DL_FUNC) &clickpaste_funtion_6, 0},
    {"clickpaste_funtion_7", (DL_FUNC) &clickpaste_funtion_7, 0},
    {"clickpaste_funtion_8", (DL_FUNC) &clickpaste_funtion_8, 0},
    {"clickpaste_funtion_9", (DL_FUNC) &clickpaste_funtion_9, 0},
    {"clickpaste_funtion_10", (DL_FUNC) &clickpaste_funtion_10, 0},
    {"clickpaste_funtion_11", (DL_FUNC) &clickpaste_funtion_11, 0},
    {"clickpaste_funtion_12", (DL_FUNC) &clickpaste_funtion_12, 0},
    {"clickpaste_enter_1", (DL_FUNC) &clickpaste_enter_1, 0},
    {"clickpaste_backspace_1", (DL_FUNC) &clickpaste_backspace_1, 0},
    {"clickpaste_delete_1", (DL_FUNC) &clickpaste_delete_1, 0},
    {"clickpaste_control_a", (DL_FUNC) &clickpaste_control_a, 0},
    {"clickpaste_alter_1", (DL_FUNC) &clickpaste_alter_1, 0},
    {"clickpaste_pageup_1", (DL_FUNC) &clickpaste_pageup_1, 0},
    {"clickpaste_pagedown_1", (DL_FUNC) &clickpaste_pagedown_1, 0},
    {"clickpaste_escape_1", (DL_FUNC) &clickpaste_escape_1, 0},
    {"clickpaste_paste_1", (DL_FUNC) &clickpaste_paste_1, 0},
    {"clickpaste_RightClick", (DL_FUNC) &clickpaste_RightClick, 2},
    {"clickpaste_SingleClick", (DL_FUNC) &clickpaste_SingleClick, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_clickpaste(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
